### ISSUE TITLE
iOS 13 Reorienting screen can put sim in corner

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/phet-core#65] opened 2019-08-22 15:13 UTC
Found when looking at https://github.com/phetsims/phet-core/issues/64.
If you start a sim in portrait, move to landscape, and then move back to portrait, the sim will shift to take up only the upper left corner of the screen.  You must be out of full screen to achieve this, but once you have, full screen will show the bug as well.
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/63526680-04ce4200-c4bd-11e9-9d87-e53700b67608.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/63526682-04ce4200-c4bd-11e9-92a2-3bfde46c42d9.png)

**Comment by ariel-phet** [comment] 2019-09-03 20:11
@jonathanolson said today he will investigate while he has the iOS 13 iPad

**Comment by jonathanolson** [comment] 2019-09-05 17:13
Should be fixed in master (as part of the commit for https://github.com/phetsims/phet-core/issues/64), can you verify?

**Comment by KatieWoe** [comment] 2019-09-05 20:43
Looks good on master.  Checked two different sims

**Comment by KatieWoe** [comment] 2019-09-17 16:08
For https://github.com/phetsims/QA/issues/427.  If you have the sim in portrait.  Lock the iPad by pressing the upper right button, and then unlock it, the sim will be in the corner.  If you reorient it fixes itself.

**Comment by jonathanolson** [comment] 2019-09-18 21:37
> For phetsims/QA#427. If you have the sim in portrait. Lock the iPad by pressing the upper right button, and then unlock it, the sim will be in the corner. If you reorient it fixes itself.

This does look like an issue, however iPadOS is reporting the incorrect window.innerWidth and window.innerHeight, so it's not just an event listener that would be needed. I haven't figured out a workaround yet.

**Comment by jonathanolson** [comment] 2019-09-19 17:20
I haven't found a working work-around for this. We properly receive the events that the sim has resized, but we're being given buggy information (even after), so I'm somewhat at a loss of how to fix it besides submitting a bug report.

**Comment by jonathanolson** [comment] 2019-10-01 15:33
I can't reproduce this on my iPhone. Can we verify if this is a problem on the live 13.1 iPadOS?

**Comment by KatieWoe** [comment] 2019-10-02 15:27
It does happen on the live iPadOS.  Can confirm that it is not an issue on iPhone

**Comment by jonathanolson** [comment] 2019-10-02 17:23
I can look into potential workarounds (that might not be pretty or performant at all), but I can't see any other avenues besides that or "wait for Apple to fix it". @ariel-phet thoughts?

**Comment by samreid** [comment] 2019-10-03 16:23
Have we given Apple a self-contained reproducible example and bug report?

**Comment by jonathanolson** [comment] 2019-10-03 16:24
Not for this issue yet.

**Comment by ariel-phet** [comment] 2019-10-08 19:01
Considering @KatieWoe comment https://github.com/phetsims/phet-core/issues/65#issuecomment-532289924 this now seems like a less likely use case, and reorienting fixes the condition. Closing since does not seem realistic/worth fixing.

**Closed by ariel-phet** 2019-10-08 19:01 UTC
Labels: type:bug
