### ISSUE TITLE
iOS 13 Full Screen enabled

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/phet-core#64] opened 2019-08-14 19:17 UTC
When looking at sims in the iOS 13 beta, we noticed that the full screen option is available in the phet menu.  It generally looks poor, but does not behave quite as badly as previous iterations from what I saw in my quick testing.
@samreid requested a user-agent check.  These are the results:
User-agent header sent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

**Comment by samreid** [comment] 2019-08-14 19:21
Is this running on a device or simulator?

**Comment by KatieWoe** [comment] 2019-08-14 19:22
Device.  Using the beta version of ios 13

**Comment by jonathanolson** [comment] 2019-08-14 19:57
Interesting user agent. I'd be curious to see the user agent of newer desktop/laptop Safari betas. I'll check around at whether this change was made to stifle lots of iOS-detection code.

**Comment by jonathanolson** [comment] 2019-08-14 19:57
I'd also like to know what device was used, this may be different based on iPhones vs iPads.

**Comment by KatieWoe** [comment] 2019-08-14 20:32
The device was a new iPad that @oliver-phet ordered the other day.

**Comment by oliver-phet** [comment] 2019-08-14 20:38
That would be a iPad 9.7 (6th generation 2018) model number A1893.

**Comment by jonathanolson** [comment] 2019-08-14 20:54
https://www.macrumors.com/2019/06/06/safari-on-ipados-optimized-for-desktop-websites/ indicates that it's an intentional change for iPads, to display/handle things more like a desktop browser would. @ariel-phet, thoughts on whether this is desirable on newer iPad iOS versions to NOT detect as mobile safari?

It may be worth an investigation into what we are using that detection for.

**Comment by ariel-phet** [comment] 2019-08-22 05:47
@KatieWoe you said:

> 
 It generally looks poor, but does not behave quite as badly as previous iterations from what I saw in my quick testing.

Can you be a bit more specific about what the issues are in full screen with this version?

**Comment by KatieWoe** [comment] 2019-08-22 15:07
https://drive.google.com/file/d/1pM4t8-t05xMBaf3mJ_y1I4b2PhTEtZKM/view?usp=sharing
This video shows some of the behavior.  In general, the biggest thing relating to full screen was that it leaves a large black space at the bottom of the screen.  Reorienting the screen can solve this.

**Comment by jessegreenberg** [comment] 2019-08-29 17:14
I found 18 usages of `platform.mobileSafari` in sims. Most related to performance/memory/enabling webgl. I found two usages related to initializing sound that may be important. Some a11y features used to be disabled on mobileSafari because they were broken/unsuported on that browser. Those have since been removed but it was very useful to have that platform info.

**Comment by Denz1994** [comment] 2019-08-29 19:08
From dev meeting: 08/29/19

@jonathanolson mentioned it would be worth checking all the current detection methods and check against iOS 13 for what would be useful for desktop versions. We should start pushing on this before full release so testing is done during maintenance releases.

**Comment by jonathanolson** [comment] 2019-09-05 16:16
iOS/iPadOS 13, more detailed notes at https://developer.apple.com/documentation/safari_release_notes/safari_13_beta_6_release_notes

Full screen (https://github.com/phetsims/phet-core/issues/64) and orientation (https://github.com/phetsims/phet-core/issues/65) issues: Seems like using the new Visual Viewport API and other listeners helps to detect the "resulting" size. The full screen feature seems to be working nicely, and I think would be fine to leave for iPadOS 13. @KatieWoe the above commit I believe fixes this, can we collaborate to check this (I can drop off the iPad today if that helps).

Performance and visual changes:

- Energy Skate Park seems slow either way. We'll want to test memory usage to see if the backing scale causes memory crashes (I didn't see a crash). @KatieWoe what iPads would we need to check to see if we run into memory crash sisues?
- Expression Exchange: coins look good without the mipmap flag changing
- Fractions games: reward node seems to have acceptable performance on my test iPad, do we need detection here?
- Function Builder: The graphical bug https://github.com/phetsims/function-builder/issues/35 is not present, shouldn't need to worry
- Gravity and Orbits: performance doesn't seem affected by feature detection
- Projectile Motion: performance seems unaffected/acceptable
- Wave Interference / Waves Intro: @samreid how can I check the performance here?

Accessibility may have gotten updates ("Improved iPad hardware keyboard support for websites including focus navigation and scrolling with the arrow keys."), so it would be good to check anything related to a11y. @jessegreenberg, what level of testing do you think would be warranted for iOS/iPadOS 13

Tambo/vibe have mobile Safari detection, and I don't have a good enough idea of whether this would break anything related to iPadOS 13 (sounds seemed to be working). @jbphet it's probably worth checking into whether the incorrect detection throws things off.

iOS/iPadOS 13 also include "pointer" events support, so it will be taking a different codepath internally for most input events. I think any major issues would have been noticed by now.

Relevant for developers, they also added an API for loading ES6 modules.

**Comment by jonathanolson** [comment] 2019-09-05 17:09
Also, I can look more into detection. It looks like there are certain hardware-detectable levels of WebGL support (e.g. maximum viewport size) that might be usable as a proxy of performance, but that's unclear.

**Comment by jessegreenberg** [comment] 2019-09-05 17:22
> @jessegreenberg, what level of testing do you think would be warranted for iOS/iPadOS 13

Bluetooth keyboards on iOS were broken because keycodes were not reported on that platform, so we are hiding the keyboard help dialog there. If we can use BASE or friction on iOS with a bluetooth keyboard we can be certain this problem is resolved. Or maybe we can just decide it is acceptable to show the dialog anyway.

**Comment by KatieWoe** [comment] 2019-09-05 18:07
@jonathanolson anytime today I can work with you on the iOS 13 checks.  I would need the device as it is the only one with iOS 13 on it.

**Comment by jonathanolson** [comment] 2019-09-05 18:17
I'll plan to drop it off after dev meeting.

**Comment by jbphet** [comment] 2019-09-09 23:00
> @jbphet it's probably worth checking into whether the incorrect detection throws things off.

It does.  The problem it causes was already found by QA and reported in https://github.com/phetsims/tambo/issues/78 (nice work @KatieWoe).  I just ran several experiments, and I believe that I can rewrite the code that was detecting Mobile Safari to work more generally, but it will require QA to verify it and a maintenance release once it's ready.  The details of the problem and the fix will be in the tambo issue.

**Comment by jbphet** [comment] 2019-09-10 17:55
The platform-specific code for sound support has been removed.

**Comment by jessegreenberg** [comment] 2019-09-17 21:20
In https://github.com/phetsims/QA/issues/428 @KatieWoe confirmed that bluetooth keyboards work well with our sims on iOS 13 with Safari.

**Comment by jonathanolson** [comment] 2019-09-26 15:20
@ariel-phet is there anything else to do? Should we have a conversation about whether I should go more down the route of detection?

**Comment by jessegreenberg** [comment] 2019-09-27 15:15
The a11y team found another case where it would be nice to detect mobile iOS. It would be helpful to have that detection in the future if possible.

Here is one recommendation on how to detect post iOS 13:
https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct

**Comment by jonathanolson** [comment] 2019-10-01 18:13
Using `navigator.maxTouchPoints > 1` sounds like a fairly decent way to detect right now, as long as newer desktop Safari wouldn't switch to increase that number.

**Comment by ariel-phet** [comment] 2019-10-08 18:58
After speaking with @jonathanolson I think we likely need a detection strategy again, and consider disabling full screen whenever we are on an iPad (since that has several problematic associated issues and we were disabling this feature in the past).

**Comment by jonathanolson** [comment] 2019-10-09 18:28
Fixed in master above. @jbphet we'll use the above commit (https://github.com/phetsims/phet-core/commit/91bb985a5eb37cff9b31836af7ddcace8be32a34) in our maintenance release. It's written so it shouldn't be dependent on es5/es6 or other historical factors.

**Comment by ariel-phet** [comment] 2019-10-10 01:37
Note for @jonathanolson and @jbphet that #67 and #66 should be tested as part of the maintenance release (if full screen is disabled both these issues should basically become irrelevant).

**Comment by lmulhall-phet** [comment] 2019-10-14 23:04
For https://github.com/phetsims/QA/issues/438, QA would like to know if we should see a fullscreen option in the PhET menu on iOS 13 (iPhoneOS 13).

We are seeing a fullscreen option in the PhET menu on iPadOS 13.

**Comment by jonathanolson** [comment] 2019-10-31 15:14
This was handled with the maintenance releases.

**Closed by jonathanolson** 2019-10-31 15:14 UTC
Labels: dev:maintenance-release, priority:2-high, type:bug
