### ISSUE TITLE
inherit confuses instanceof

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#24] opened 2016-07-20 04:55 UTC
Starting in https://github.com/phetsims/phet-io/issues/489#issuecomment-233836472 and for the new few comments the following problem was described (test can replace the bottom part of DielectricMaterial.js in CLB):

```js
  var air = new DielectricMaterial( 'air', CLBConstants.EPSILON_AIR, CLBConstants.AIR_COLOR, tandem.createTandem( 'air' ) );

  console.log( air instanceof DielectricMaterial ); // true
  var v = inherit( Object, DielectricMaterial, {}, {

    AIR: air,

    CustomDielectricMaterial: function( dielectricConstant ) {
      return new DielectricMaterial( 'Custom', dielectricConstant,
        CLBConstants.CUSTOM_DIELECTRIC_COLOR, null ); // TODO: tandem
    }

  } );

  console.log( air instanceof DielectricMaterial ); // false
  
  var air2 = new DielectricMaterial( 'air', CLBConstants.EPSILON_AIR, CLBConstants.AIR_COLOR, tandem.createTandem( 'air' ) );
  
  console.log( air2 instanceof DielectricMaterial ); // true
  return v;
```

Note that
```js
console.log( air instanceof DielectricMaterial );
```
is true before inherit then false after inherit.

Does this mean any of the following?
a) We have a bug in our inherit implementation?
b) We must create static instances after inherit is called?
c) Something else?

Any ideas @jessegreenberg @jonathanolson @jbphet @pixelzoom @andrewadare?  I'll flag for developer meeting in case it's not closed by then.

**Comment by pixelzoom** [comment] 2016-07-20 05:20
I don't understand the above example. Presumably DielectricMaterial.js defines the constructor and already calls inherit.  Why would you call inherit again? And why would you expect it to work if you did? Messing with the constructor property (line 50 in inherit.js) is certainly going to cause instanceof to fail for existing instances -- which is what you're seeing.

**Comment by pixelzoom** [comment] 2016-07-20 05:25
Here's a simpler example, where lines 21-23 are what you're doing by calling inherit a second time:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

**Comment by samreid** [comment] 2016-07-20 05:31
To run this test:

1) copy and paste this into DielectricMaterial.js

```js
// Copyright 2015, University of Colorado Boulder

/**
 * Base class and subclasses for dielectric materials. All subclasses for "real" materials are immutable.
 * The subclass for a "custom" material has a mutable dielectric constant.
 *
 * NOTE: Air is the only dielectric material needed for now. Dielectrics not being ported at this time.
 * However, a basic custom dielectric is used to calculate the maximum number of charges possible on a capacitor.
 *
 * @author Chris Malley (cmalley@pixelzoom.com)
 * @author Jesse Greenberg
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );
  var CLBConstants = require( 'CAPACITOR_LAB_BASICS/common/CLBConstants' );
  var capacitorLabBasics = require( 'CAPACITOR_LAB_BASICS/capacitorLabBasics' );
  var Tandem = require( 'TANDEM/Tandem' );
  var Color = require( 'SCENERY/util/Color' );

  // A new tandem instance is required here since the solutes are created statically.
  var tandem = Tandem.createStaticTandem( 'dielectrics' );

  /**
   * @constructor
   *
   * @param {string} name - the type of dielectric
   * @param {number} dielectricConstant
   * @param {string|color} color
   * @param {Tandem} tandem
   */
  function DielectricMaterial( name, dielectricConstant, color, tandem ) {

    // @public (read-only)
    this.name = name;
    this.color = new Color( color );
    this.dielectricConstant = dielectricConstant;

    tandem && tandem.addInstance( this );
  }

  capacitorLabBasics.register( 'DielectricMaterial', DielectricMaterial );

  var air = new DielectricMaterial( 'air', CLBConstants.EPSILON_AIR, CLBConstants.AIR_COLOR, tandem.createTandem( 'air' ) );

  console.log( air instanceof DielectricMaterial ); // true
  var v = inherit( Object, DielectricMaterial, {}, {

    AIR: air,

    CustomDielectricMaterial: function( dielectricConstant ) {
      return new DielectricMaterial( 'Custom', dielectricConstant,
        CLBConstants.CUSTOM_DIELECTRIC_COLOR, null ); // TODO: tandem
    }

  } );

  console.log( air instanceof DielectricMaterial ); // false

  var air2 = new DielectricMaterial( 'air', CLBConstants.EPSILON_AIR, CLBConstants.AIR_COLOR, tandem.createTandem( 'air' ) );

  console.log( air2 instanceof DielectricMaterial ); // true
  return v;
} );
```
2. Launch http://localhost/capacitor-lab-basics/capacitor-lab-basics_en.html?ea&brand=phet
3. Notice that it prints out true, false, true.

**Comment by pixelzoom** [comment] 2016-07-20 05:32
And that's what I would expect.  If you call `inherit` after creating instances, the instanceof test will fail for those instances, because you've changed the constructor's prototype property.

**Comment by samreid** [comment] 2016-07-20 05:34
So is DielectricMaterial.js (as it is checked in to master right now, and I will reproduce the critical bits below) an example of an antipattern because it creates instances incompatible with instanceof?

```js
  return inherit( Object, DielectricMaterial, {}, {

    AIR: new DielectricMaterial( 'air', CLBConstants.EPSILON_AIR, CLBConstants.AIR_COLOR, tandem.createTandem( 'air' ) ),

    CustomDielectricMaterial: function( dielectricConstant ) {
      return new DielectricMaterial( 'Custom', dielectricConstant,
        CLBConstants.CUSTOM_DIELECTRIC_COLOR, null ); // TODO: tandem
    }

  } );
```

If this is truly an antipattern, are we using it elsewhere in our codebase?  What is the correct alternative?

**Comment by pixelzoom** [comment] 2016-07-20 05:36
I would expect `Dielectric.AIR instanceof Dielectric` to return `false` in the current implementation. And yes, if you need instanceof to work properly, then this is an antipattern.

**Comment by samreid** [comment] 2016-07-20 05:37
Beer's Law Lab's Solute.js shows one way to assign a static after the inherit call (this is the workaround in my tests above:

```js
  inherit( Object, Solute, {

    // @public gets the saturated concentration, in mol/L
    getSaturatedConcentration: function() {
      return this.colorScheme.maxConcentration;
    }
  } );

  // Specific solutes ===========================================

  // A new tandem instance is required here since the solutes are created statically.
  var tandem = Tandem.createStaticTandem( 'solutes' );

  Solute.DRINK_MIX = new Solute(
```

**Comment by pixelzoom** [comment] 2016-07-20 05:38
I think what's done in beer-law-lab.Solute is a fine way to create static instances. I don't view this as a workaround.

**Comment by samreid** [comment] 2016-07-20 05:39
> And yes, if you need instanceof to work properly, then this is an antipattern.

Generally, `instanceof` has served our project well and we should endeavor to keep it working properly.  Is there an inexpensive way to detect occurrences of where an instance of type T is instantiated before the inherit call (including but not limited to: as a parameter in the static part of the inherit call)?

**Comment by samreid** [comment] 2016-07-20 05:44
In DielectricMaterial.js, I've applied the Solute-like solution in the above commit.

**Comment by pixelzoom** [comment] 2016-07-20 05:44
Write a bash script to iterate over all .js files in all repos, and and checks for occurrences of "new T", where T is the basename of the file.

**Comment by pixelzoom** [comment] 2016-07-20 05:45
Write a bash script to iterate over all .js files in all repos, and and check for occurrences of "new T", where T is the basename of the file.  Then manually inspect all such occurrences.

**Comment by samreid** [comment] 2016-07-20 05:48
Good idea, I can take a look at that in the future.  Reassigned to me and removing developer-meeting label for now.  I may add the label back if I'm seeing many occurrences of this antipattern and it requires further discussion.

**Comment by samreid** [comment] 2016-07-20 05:48
The high-priority label is to remind me to look at this soon, while it is fresh in our minds, and because this shouldn't take too long.

**Comment by samreid** [comment] 2016-07-20 06:02
Note to self: we may be able to detect the most likely form of the anti pattern by adding an assertion to inherit.

**Comment by pixelzoom** [comment] 2016-07-20 06:04
This script will identify calls to 'new T' inside file T.js:

```
#!/bin/bash
#====================================================================================================
#
# Finds calls to 'new T' inside file T.js, which may be examples of the anti-patterns identified
# in https://github.com/phetsims/phet-core/issues/24
#
# Author: Chris Malley (PixelZoom, Inc.)
#
#====================================================================================================

CHIPPER_BIN=`dirname "${BASH_SOURCE[0]}"`
ROOT_DIR=${CHIPPER_BIN}/../..
cd ${ROOT_DIR}

sourceFiles=`find . -name "*.js" -print | grep -v node_modules | grep -v sherpa | grep -v "scenery/snapshots" | grep -v "litmus/jsmol"`

for sourceFile in ${sourceFiles}
do

  # get the file's basename
  fileBasename=`basename ${sourceFile}`

  # strip off .js
  fileBasename=${fileBasename%.js}

  # look for instantiation of instances inside the file
  grep -H "new ${fileBasename}(" ${sourceFile}
done
```

**Comment by pixelzoom** [comment] 2016-07-20 06:11
Also worth pointing out that the name of `DieletricMaterial.CustomDielectricMaterial` is misleading, it looks like a constructor since it begins with uppercase, when in fact it's a factory function. This anti-pattern appears throughout CLB. Reported in https://github.com/phetsims/capacitor-lab-basics/issues/123.

**Comment by pixelzoom** [comment] 2016-07-20 06:15
Using the script in https://github.com/phetsims/phet-core/issues/24#issuecomment-233845939, the only problem I identified is `bending-light.Substance`.

**Comment by pixelzoom** [comment] 2016-07-20 06:16
Using the script in #24 (comment), the only problem I identified is in bending-light.Substance:

```js
return inherit( Object, Substance, {}, {
    AIR: new Substance( airString, 1.000293, false, false ),
    WATER: new Substance( waterString, 1.333, false, false ),
    GLASS: new Substance( glassString, 1.5, false, false ),
    DIAMOND: new Substance( diamondString, DIAMOND_INDEX_OF_REFRACTION_FOR_RED_LIGHT, false, false ),
    MYSTERY_A: new Substance( mysteryAString, DIAMOND_INDEX_OF_REFRACTION_FOR_RED_LIGHT, true, false ),
    MYSTERY_B: new Substance( mysteryBString, 1.4, true, false ),
    DIAMOND_INDEX_OF_REFRACTION_FOR_RED_LIGHT: DIAMOND_INDEX_OF_REFRACTION_FOR_RED_LIGHT
  } );
```

**Comment by pixelzoom** [comment] 2016-07-20 06:20
Here's a refinement to the script in https://github.com/phetsims/phet-core/issues/24#issuecomment-233845939...

Change these lines:

```
  # look for instantiation of instances inside the file
  grep -H "new ${fileBasename}(" ${sourceFile}
```

To this:

```
  # look for instantiation of static instances inside the file
  grep -H ": new ${fileBasename}(" ${sourceFile}
```

By adding ': ' before the `new` call, we're looking for static instances.

**Comment by pixelzoom** [comment] 2016-07-20 06:21
With the above modification, here's the script output:

```
./bending-light/js/common/model/Substance.js:    AIR: new Substance( airString, 1.000293, false, false ),
./bending-light/js/common/model/Substance.js:    WATER: new Substance( waterString, 1.333, false, false ),
./bending-light/js/common/model/Substance.js:    GLASS: new Substance( glassString, 1.5, false, false ),
./bending-light/js/common/model/Substance.js:    DIAMOND: new Substance( diamondString, DIAMOND_INDEX_OF_REFRACTION_FOR_RED_LIGHT, false, false ),
./bending-light/js/common/model/Substance.js:    MYSTERY_A: new Substance( mysteryAString, DIAMOND_INDEX_OF_REFRACTION_FOR_RED_LIGHT, true, false ),
./bending-light/js/common/model/Substance.js:    MYSTERY_B: new Substance( mysteryBString, 1.4, true, false ),
./capacitor-lab-basics/js/common/model/DielectricMaterial.js:    AIR: new DielectricMaterial( 'air', CLBConstants.EPSILON_AIR, CLBConstants.AIR_COLOR, tandem.createTandem( 'air' ) ),
./dot/js/Matrix3.js:        var instance = pool.length ? pool.pop() : new Matrix3();
./dot/js/Vector2.js:  Vector2.ZERO = assert ? new Immutable( 0, 0 ) : new Vector2( 0, 0 );
./dot/js/Vector2.js:  Vector2.X_UNIT = assert ? new Immutable( 1, 0 ) : new Vector2( 1, 0 );
./dot/js/Vector2.js:  Vector2.Y_UNIT = assert ? new Immutable( 0, 1 ) : new Vector2( 0, 1 );
./dot/js/Vector3.js:  Vector3.ZERO = assert ? new Immutable( 0, 0, 0 ) : new Vector3( 0, 0, 0 );
./dot/js/Vector3.js:  Vector3.X_UNIT = assert ? new Immutable( 1, 0, 0 ) : new Vector3( 1, 0, 0 );
./dot/js/Vector3.js:  Vector3.Y_UNIT = assert ? new Immutable( 0, 1, 0 ) : new Vector3( 0, 1, 0 );
./dot/js/Vector3.js:  Vector3.Z_UNIT = assert ? new Immutable( 0, 0, 1 ) : new Vector3( 0, 0, 1 );
./dot/js/Vector4.js:  Vector4.ZERO = assert ? new Immutable( 0, 0, 0, 0 ) : new Vector4( 0, 0, 0, 0 );
./dot/js/Vector4.js:  Vector4.X_UNIT = assert ? new Immutable( 1, 0, 0, 0 ) : new Vector4( 1, 0, 0, 0 );
./dot/js/Vector4.js:  Vector4.Y_UNIT = assert ? new Immutable( 0, 1, 0, 0 ) : new Vector4( 0, 1, 0, 0 );
./dot/js/Vector4.js:  Vector4.Z_UNIT = assert ? new Immutable( 0, 0, 1, 0 ) : new Vector4( 0, 0, 1, 0 );
./dot/js/Vector4.js:  Vector4.W_UNIT = assert ? new Immutable( 0, 0, 0, 1 ) : new Vector4( 0, 0, 0, 1 );
./masses-and-springs/js/masses-and-springs/model/Body.js:    MOON: new Body( bodyMoonString, 1.62 ),
./masses-and-springs/js/masses-and-springs/model/Body.js:    EARTH: new Body( bodyEarthString, 9.81 ),
./masses-and-springs/js/masses-and-springs/model/Body.js:    JUPITER: new Body( bodyJupiterString, 24.79 ),
./masses-and-springs/js/masses-and-springs/model/Body.js:    PLANET_X: new Body( bodyPlanetXString, 14.2 ),
./masses-and-springs/js/masses-and-springs/model/Body.js:    ZERO_G: new Body( bodyZeroGString, 0 ),
./masses-and-springs/js/masses-and-springs/model/Body.js:    CUSTOM: new Body( bodyCustomString, null )
./molecule-shapes/js/common/model/GeometryConfiguration.js:    0: new GeometryConfiguration( geometryEmptyString, [] ),
./molecule-shapes/js/common/model/GeometryConfiguration.js:    1: new GeometryConfiguration(
./molecule-shapes/js/common/model/GeometryConfiguration.js:    2: new GeometryConfiguration(
./molecule-shapes/js/common/model/GeometryConfiguration.js:    3: new GeometryConfiguration(
./molecule-shapes/js/common/model/GeometryConfiguration.js:    4: new GeometryConfiguration(
./molecule-shapes/js/common/model/GeometryConfiguration.js:    5: new GeometryConfiguration(
./molecule-shapes/js/common/model/GeometryConfiguration.js:    6: new GeometryConfiguration(
./scenery/js/util/Color.js:    return colorSpec instanceof Color ? colorSpec : new Color( colorSpec );
./scenery-phet/js/MultiLineText.js: * Example: new MultiLineText( 'Hello\nWorld', { align: 'left', font: new PhetFont(20), fill: 'red' } );
./scenery-phet/js/PhetFont.js:    // convenience constructor: new PhetFont( {number|string} size )
./sugar-and-salt-solutions/js/common/model/DispenserType.js:    'SALT': new DispenserType( 11, 17 ),
./sugar-and-salt-solutions/js/common/model/DispenserType.js:    'SUGAR': new DispenserType( 6, 1, 8 ),
./sugar-and-salt-solutions/js/common/model/DispenserType.js:    'GLUCOSE': new DispenserType( 6, 1, 8 ),
./sugar-and-salt-solutions/js/common/model/DispenserType.js:    'SODIUM_NITRATE': new DispenserType( 11, 7, 8 ),
./sugar-and-salt-solutions/js/common/model/DispenserType.js:    'CALCIUM_CHLORIDE': new DispenserType( 20, 17 )
```

**Comment by pixelzoom** [comment] 2016-07-20 06:23
masses-and-springs.Body is also a problem.

**Comment by pixelzoom** [comment] 2016-07-21 13:34
Labeling for developer-meeting, so that all developers are aware of this anti-pattern.

**Comment by pixelzoom** [comment] 2016-07-21 17:53
So to summarize... The 2 problems are masses-and-springs.Body and bending-light.Substance. 

Decided to leave this on developer-meeting until next week, to review with developers who weren't at 7/21/16 meeting.

**Comment by pixelzoom** [comment] 2016-07-21 18:28
Issues have been created for specific problems in sims.  So this issue can be closed after we review it at next developer meeting.

**Comment by pixelzoom** [comment] 2016-07-21 18:55
@jessegreenberg @mattpen We discussed this at 7/21/16, and @ariel-phet requested to keep this open until you've had a chance to familiarize yourself with this issue.

In summary:

The problem: A type is not fully defined until inherit is called. If you create instances of a type before calling inherit, those instances will fail an `instanceof` test.

The solution: Create instances only after `inherit` has been called.

Please verify that you understand the problem and solution.  See https://github.com/phetsims/masses-and-springs/issues/15 and https://github.com/phetsims/bending-light/issues/349 for concrete examples.  

The last person to unassign themselves can close this issue.

**Comment by jessegreenberg** [comment] 2016-07-25 18:03
Understood, thanks for leaving this open to review.  I observed the issue by reproducing via https://github.com/phetsims/phet-core/issues/24#issuecomment-233842010, this makes sense.

Assigning to @mattpen.

**Comment by mattpen** [comment] 2016-07-27 16:32
I have reviewed and understood the issue.  Thanks for the detailed explanation.

> The last person to unassign themselves can close this issue.

**Closed by mattpen** 2016-07-27 16:32 UTC
Labels: meeting:developer, priority:2-high
