### ISSUE TITLE
Is `{}` the correct default for `ParentOptions` in `optionize`? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#114] opened 2022-04-06 15:30 UTC
The signature of `optionize` is currently:

```js
function optionize<ProvidedOptions, // eslint-disable-line no-redeclare
  SelfOptions = ProvidedOptions,
  ParentOptions = {},
  KeysUsedInSubclassConstructor extends keyof ParentOptions = never>
```

I'm wondering if `{}` is the correct default for ParentOptions.   Shouldn't it default to ProvidedOptions & SelfOptions?

For example... I find myself having to use this pattern in many places, and I see the same in other developers' code:

```js
  const arrowShapeOptions = optionize<ArrowNodeOptions, {}, ArrowNodeOptions>( {
    doubleHead: true
  }, options.arrowNodeOptions );
```

Why not simply this?

```js
  const arrowShapeOptions = optionize<ArrowNodeOptions>( {
    doubleHead: true
  }, options.arrowNodeOptions );
```

@zepumph @samreid thoughts?

**Comment by zepumph** [comment] 2022-04-06 15:33
I think the default could be ProvidedOptions, but it specifically shouldn't include `SelfOptions`. What do you think about that? It may be a hard thing to change usages of.

**Comment by samreid** [comment] 2022-04-06 15:46
I was experimenting with lint rules, and one of the lint rules flagged all our `{}` types, basically saying "this doesn't mean what you think it means".  So we may make adjustments around that.

**Comment by pixelzoom** [comment] 2022-04-27 01:34
Over in https://github.com/phetsims/geometric-optics/issues/433#issuecomment-1110110841, @samreid mentioned that he doesn't like the pattern `optionize<SomeType, {}, SomeType>`.  If a different pattern is desired, we should addresses this soon, since that pattern is proliferating.

**Comment by samreid** [comment] 2022-04-27 02:55
> @samreid mentioned that he doesn't like the pattern `optionize<SomeType, {}, SomeType>`.

That is not an accurate characterization of my point from that issue. My concern was that `optionize` is being used inappropriately in that case.  In that case, optionize is used in the global constants file like so:

```ts
  CREDITS: optionize<CreditsData, {}, CreditsData>()( {
    leadDesign: 'Amy Rouinfar, Michael Dubson',
    softwareDevelopment: 'Sarah Chang, Chris Malley (PixelZoom, Inc.), Martin Veillette',
    team: 'Chris Klusendorf, Diana L\u00f3pez Tavares, Ariel Paul, Kathy Perkins',
    qualityAssurance: 'Steele Dalton, Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
    graphicArts: 'Megan Lai'
  } ),
```

This does not seem an appropriate usage of `optionize`, since there is no notion of SelfOptions, ParentOptions, Defaults, a 2nd parameter, etc. In that issue, I suggested 3 better ways to enforce the CreditsData type which do not use `optionize`.  Here is a 4th way which is also better than using `optionize`:

```ts
  CREDITS: _.identity<CreditsData>( {
    leadDesign: 'Amy Rouinfar, Michael Dubson',
    softwareDevelopment: 'Sarah Chang, Chris Malley (PixelZoom, Inc.), Martin Veillette',
    team: 'Chris Klusendorf, Diana L\u00f3pez Tavares, Ariel Paul, Kathy Perkins',
    qualityAssurance: 'Steele Dalton, Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
    graphicArts: 'Megan Lai'
  } ),
```

As to the more general point about liking or disliking `optionize<SomeType, {}, SomeType>`, I haven't reviewed cases other than the one mentioned above to see if they seem appropriate.

**Comment by samreid** [comment] 2022-04-28 16:12
I observed that `_.identity` did not have as good code navigation in WebStorm (for unknown reasons), so I added phet-core/identity.ts.

**Comment by pixelzoom** [comment] 2022-04-29 02:35
I don't agree that something like identity.ts is needed.  

Help me understand why this is OK (example from TimeControlNode.ts, similar usages throughout common code):

```js
    this.playPauseStepButtons = new PlayPauseStepButtonGroup( isPlayingProperty,
      optionize<PlayPauseStepButtonGroupOptions, {}, PlayPauseStepButtonGroupOptions>()( {
        tandem: options.tandem.createTandem( 'playPauseStepButtons' )
      }, options.playPauseStepButtonOptions ) );
    children.push( this.playPauseStepButtons );
```

... and this (from GOConstants.ts) is an "inappropriate" use:

```js
CREDITS: optionize<CreditsData, {}, CreditsData>()( {
    leadDesign: 'Amy Rouinfar, Michael Dubson',
    softwareDevelopment: 'Sarah Chang, Chris Malley (PixelZoom, Inc.), Martin Veillette',
    team: 'Chris Klusendorf, Diana L\u00f3pez Tavares, Ariel Paul, Kathy Perkins',
    qualityAssurance: 'Steele Dalton, Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
    graphicArts: 'Megan Lai'
  } ),
```

In both cases, `optionize` is creating an object literal that conforms to an options type -- it is "optionizing".   And the important aspect is type checking, not the number of arguments or "merging" of object literals. 

And if the latter example, is not a legitimate use, then why does `optionize` work with 1 argument?

**Comment by samreid** [comment] 2022-04-29 04:39
I see two reasonable pathways forward.  

#### (I) Adapting `optionize` so that can be used to merge options when it is given one type parameter.

As proposed in the top comment. This was also advocated for in https://github.com/phetsims/phet-core/issues/105.  Perhaps it would be best to hear from @zepumph about whether that is practical and how it would be done exactly.  Both code examples in the previous comment would be more palatable if they took one type parameter.  But would still be unfortunate that you have to provide extra `()`.

#### (II) Add a separate method which is to be used for combining options like merge. 

In this case, we would have one method (a) `optionize` for use in combining providedOptions + defaults to compute options, like the 14 examples in WilderOptionsPatterns and introduce a separate method (b) `mergeOptions` for populating options elsewhere.  `mergeOptions` could be used like so:

```ts
    this.playPauseStepButtons = new PlayPauseStepButtonGroup( isPlayingProperty,
      mergeOptions<PlayPauseStepButtonGroupOptions>( {
        tandem: options.tandem.createTandem( 'playPauseStepButtons' )
      }, options.playPauseStepButtonOptions ) );
```

Note this also has the benefit that you don't need the unfortunate extra `()` that `optionize` requires.

Here is a rough draft but apparently working implementation of `mergeOptions`.  There may be a better way to implement it, but this leverages the fact that `optionize<T,{},T>` appears to have the behavior we want (??).  It is also nice that you cannot accidentally call `mergeOptions` with more than one type parameter.

```ts
    function mergeOptions<T>( a: HalfOptions<{}, T>, b: T | undefined ) {
      return optionize<T, {}, T>()( a, b );
    }
```

We should discuss whether we prefer (I) one multi-purpose function (like we had with `merge`) or (II) separate functions.  Would be good to hear from multiple devs on this point.

**Comment by pixelzoom** [comment] 2022-05-06 17:33
I'd like to resolve this issue before publishing geometric-optics, so raising the priority. I've added TODOs in the relevant places in geometric-optics, see above commit.  

To summarize...

I'm currently using this pattern in GOConstants.ts, which is the same form of `optionize` used in other examples that involve > 1 arg.  The only difference here is that there is only 1 arg, and we're verifying that it conforms to the specified options type.

```
  CREDITS: optionize<CreditsData, {}, CreditsData>()( {
    ...
  } ),
```

@samreid has proposed an entirely different function, `identity`.  As I understand it, he's proposing a different function because he feels that it's inappropriate to use the type-checking features of `optionize` if we're not merging. (Correct me if I've misunderstood.)  I disagree, especially since `optionize` accepts a single argument, and works correctly.

```
  CREDITS: identity<CreditsData>( {
    ...
  } ),
```

I would prefer a different parameterization of `optionize`, so that we have a single function for optionizing object literals.  This seems more consistent with the goal of eventually eliminating `optionize3`.  Why wouldn't we also eventually eliminate `identity`?

```
  CREDITS: optionize<CreditsData>()( {
    ...
  } ),
```

**Comment by chrisklus** [comment] 2022-05-09 18:21
Consensus from 5/9 supplemental dev meeting:

We think there is enough usages of the case described above, often used for nested option of composed types, to make a new merge-like type to eliminate the duplication that occurs with optionize.

Also, could this work with var args?

Names discussed: `sprinkleOptions`, 

@zepumph is going to investigate this, thank you!

**Comment by pixelzoom** [comment] 2022-05-09 19:28
I made this issue moot for GOConstants.ts by factoring out typed `const`s.

**Comment by zepumph** [comment] 2022-05-09 22:50
Some more possible names. I'm trying to focus in on something like says "I combine only things of the same type to a merged version of the same original type." 

```
combineOptions
sameTypeOptions
mergeSimilar
consolidate
combine
fillInOptions
collect
collectSameOptions

**Comment by samreid** [comment] 2022-05-09 23:11
`expand` sounds like it is adding more new keys, so I'd recommend against it.

* setOptions
* specifyOptions
* I think lodash also used assignIn
* assignOptions

Not sure what is best of this list or the prior list.

**Comment by zepumph** [comment] 2022-05-09 23:15
Let's do assignOptions for now.

**Comment by zepumph** [comment] 2022-05-09 23:30
I added assignOptions and assignOptions3, and converted a few usages. I counted 88 potential candidates for converting to this, not all are good, because they are in the constructor options or a side function, but many are within the composition case we talked about today during the meeting. I think it would be good to touch base with @samreid. Do you like this? Should we convert more usages? What are the feelings here?

**Comment by pixelzoom** [comment] 2022-05-10 00:35
My 2 cents...  

My favorite of the proposed names is `combineOptions`.  

I'm not a fan of `assignOptions`, because "assignment" is a well-defined term in programming (storing a value in a location denoted by a variable name), and this is not assignment.

I might have suggested `mergeOptions`. But it's probably best to avoid "merge" because of PhET's history with `merge` - better to have an entirely different name to avoid confusion.

**Comment by zepumph** [comment] 2022-05-10 16:05
I totally agree with @pixelzoom. I would also add that "combine" gives me set-like feelings that make me think of a homogenous group. Perhaps I'm grasping for that context though. 

@samreid, please take a look around with the understanding that it will be renamed to `combineOptions`.

**Comment by zepumph** [comment] 2022-05-12 20:15
Rename above. @pixelzoom @samreid  note that it is now called combineOptions.

**Comment by pixelzoom** [comment] 2022-05-12 20:49
In the above commits:
* make the last param optional for `combineOptions` and `combineOptions3`
* used `combineOptions` and `combineOptions3` in geometric-optics

Next I'll work on using `combineOptions` and `combineOptions3` in common code.

**Comment by pixelzoom** [comment] 2022-05-12 22:29
In the above commits, I used `combineOptions` and `combineOptions3` in common code.  This was super easy for the code that I had written, because I only had to search for ", {},".   In other code, that search string identified a lot of cases where `{}` is being used instead of SelfOptions in optionize calls.

**Comment by samreid** [comment] 2022-05-13 04:27
Some review questions and comments:

- [ ] `HalfOptions<{}, Type>` would be written more simply as `Partial<Type>` in every case.
- [ ] Can we get overloading to work for us in this case?  Just have one `combineOptions` function with multiple signatures, or just one varargs `combineOptions` function?
- [ ] The type assertion `as HalfOptions<{}, Type>` isn't doing anything and should be removed.
- [ ] `combineOptions` should not call `optionize`.  We should identify the important/relevant parts out of `optionize` signature and capture it in an independent declaration in `combineOptions`.  
- [ ] Is the intended semantics that we combine a partial options with a complete options? The final argument is `b?: Type` which means it has to have all the required parts from the options type.  Is that by design and useful?
- [ ] Would we ever want to infer the type parameters of `combineOptions`?  If not, how about a lint rule that makes `combineOptions(` bad text?  I think we tried this elsewhere before?

I didn't see any problems in the usage sites, but may re-examine them after discussion of the aforementioned items.

**Comment by zepumph** [comment] 2022-06-03 22:07
All have been accomplished. Thanks for the feedback. Anything else here?

**Comment by samreid** [comment] 2022-06-06 23:04
Looks great, thanks!  Closing.

**Comment by samreid** [comment] 2022-09-08 21:33
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by samreid** [comment] 2022-09-09 18:30
I removed the extraneous TODO, closing.

**Closed by samreid** 2022-09-09 18:30 UTC
Labels: priority:2-high, status:ready-for-review, dev:typescript
